In [2]:
import torch
import random

In [5]:
x = torch.randn(2, 3, 4)
x

tensor([[[ 1.4744,  0.0600, -0.8609,  0.5235],
         [-1.3147,  0.1336, -0.7295,  0.3293],
         [ 0.5381, -0.3411, -0.5148, -0.3098]],

        [[ 1.0922, -2.0813, -0.9585, -1.0393],
         [-1.1278, -0.1916,  0.6662, -0.9143],
         [-1.9904, -1.5204, -0.9116, -1.0557]]])

In [4]:
x.view(3,10)

tensor([[ 0.6066, -0.4443,  0.4002, -0.1663,  1.3311,  0.0122,  0.8761, -0.9690,
         -0.4260,  1.0760],
        [-0.3513, -0.5783, -0.0486,  0.7539,  0.7355,  2.1542,  0.4605,  1.2659,
         -0.0042,  1.1674],
        [ 0.2439,  0.0100,  0.6099, -0.3603, -1.8676,  0.7448,  0.4151, -1.5475,
          0.8803, -0.1230]])

In [3]:
lol = torch.randn(3, 10)
lol

tensor([[-0.2097, -0.3311, -0.0400,  0.4867,  0.1042,  0.9299,  0.7677, -1.1266,
          0.5486, -1.7117],
        [-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352,  1.3515, -0.3797,
          0.2169,  0.4818],
        [-0.8894,  1.6380,  2.5008, -0.6188, -0.0733, -2.2552,  0.2813, -0.9360,
          1.0954, -0.3763]])

In [11]:
I,J = lol.shape
for j in range(J):
    print(lol[1,:j+1])

tensor([-1.3035])
tensor([-1.3035,  1.9762])
tensor([-1.3035,  1.9762,  1.4770])
tensor([-1.3035,  1.9762,  1.4770,  0.1481])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352,  1.3515])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352,  1.3515, -0.3797])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352,  1.3515, -0.3797,
         0.2169])
tensor([-1.3035,  1.9762,  1.4770,  0.1481,  0.2058,  1.7352,  1.3515, -0.3797,
         0.2169,  0.4818])


In [12]:
32//4

8

In [13]:
x = [1,2,3,4,5,6,7,8,9]
y = [2,3,4,5,6,7,8,9]

for pair in zip(x,y):
    print(pair)

(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)
(8, 9)


In [ ]:
import tiktoken
enc = tiktoken.get_encoding("cl100k_base") # this is the GPT-4 tokenizer

{b'!': 0, b'"': 1, b'#': 2, b'$': 3, b'%': 4, b'&': 5, b"'": 6, b'(': 7, b')': 8, b'*': 9, b'+': 10, b',': 11, b'-': 12, b'.': 13, b'/': 14, b'0': 15, b'1': 16, b'2': 17, b'3': 18, b'4': 19, b'5': 20, b'6': 21, b'7': 22, b'8': 23, b'9': 24, b':': 25, b';': 26, b'<': 27, b'=': 28, b'>': 29, b'?': 30, b'@': 31, b'A': 32, b'B': 33, b'C': 34, b'D': 35, b'E': 36, b'F': 37, b'G': 38, b'H': 39, b'I': 40, b'J': 41, b'K': 42, b'L': 43, b'M': 44, b'N': 45, b'O': 46, b'P': 47, b'Q': 48, b'R': 49, b'S': 50, b'T': 51, b'U': 52, b'V': 53, b'W': 54, b'X': 55, b'Y': 56, b'Z': 57, b'[': 58, b'\\': 59, b']': 60, b'^': 61, b'_': 62, b'`': 63, b'a': 64, b'b': 65, b'c': 66, b'd': 67, b'e': 68, b'f': 69, b'g': 70, b'h': 71, b'i': 72, b'j': 73, b'k': 74, b'l': 75, b'm': 76, b'n': 77, b'o': 78, b'p': 79, b'q': 80, b'r': 81, b's': 82, b't': 83, b'u': 84, b'v': 85, b'w': 86, b'x': 87, b'y': 88, b'z': 89, b'{': 90, b'|': 91, b'}': 92, b'~': 93, b'\xa1': 94, b'\xa2': 95, b'\xa3': 96, b'\xa4': 97, b'\xa5': 98, b'\

In [7]:
def bpe(mergeable_ranks, token, max_rank):
    # helper function used in get_gpt4_merges() to reconstruct the merge forest
    parts = [bytes([b]) for b in token]
    while True:
        min_idx = None
        min_rank = None
        for i, pair in enumerate(zip(parts[:-1], parts[1:])):
            rank = mergeable_ranks.get(pair[0] + pair[1])
            if rank is not None and (min_rank is None or rank < min_rank):
                min_idx = i
                min_rank = rank
        if min_rank is None or (max_rank is not None and min_rank >= max_rank):
            break
        assert min_idx is not None
        parts = parts[:min_idx] + [parts[min_idx] + parts[min_idx + 1]] + parts[min_idx + 2:]
    return parts

def recover_merges(mergeable_ranks):
    # the `merges` are already the byte sequences in their merged state.
    # so we have to recover the original pairings. We can do this by doing
    # a small BPE training run on all the tokens, in their order.
    # also see https://github.com/openai/tiktoken/issues/60
    # also see https://github.com/karpathy/minbpe/issues/11#issuecomment-1950805306
    merges = {}
    for token, rank in mergeable_ranks.items():
        if len(token) == 1:
            continue # skip raw bytes
        pair = tuple(bpe(mergeable_ranks, token, max_rank=rank))
        assert len(pair) == 2
        # recover the integer ranks of the pair
        ix0 = mergeable_ranks[pair[0]]
        ix1 = mergeable_ranks[pair[1]]
        merges[(ix0, ix1)] = rank

    return merges

In [ ]:
x = recover_merges(enc._mergeable_ranks)

{(220, 220): 256, (256, 256): 257, (72, 77): 258, (220, 83): 259, (257, 257): 260, (68, 81): 261, (256, 220): 262, (78, 77): 263, (220, 64): 264, (81, 68): 265, (64, 83): 266, (82, 83): 267, (68, 77): 268, (78, 81): 269, (259, 71): 270, (198, 198): 271, (220, 66): 272, (75, 68): 273, (220, 82): 274, (72, 83): 275, (64, 77): 276, (64, 81): 277, (64, 75): 278, (270, 68): 279, (26, 198): 280, (220, 79): 281, (220, 69): 282, (78, 84): 283, (220, 28): 284, (72, 82): 285, (257, 262): 286, (258, 70): 287, (68, 82): 288, (220, 86): 289, (72, 263): 290, (68, 67): 291, (72, 66): 292, (220, 65): 293, (220, 67): 294, (68, 83): 295, (220, 76): 296, (220, 78): 297, (197, 197): 298, (81, 78): 299, (64, 82): 300, (68, 75): 301, (66, 83): 302, (77, 67): 303, (220, 258): 304, (220, 71): 305, (268, 83): 306, (72, 67): 307, (220, 77): 308, (64, 76): 309, (260, 262): 310, (259, 78): 311, (220, 265): 312, (12, 12): 313, (220, 90): 314, (297, 69): 315, (78, 76): 316, (8, 280): 317, (72, 76): 318, (201, 198):

In [9]:
x

{(220, 220): 256,
 (256, 256): 257,
 (72, 77): 258,
 (220, 83): 259,
 (257, 257): 260,
 (68, 81): 261,
 (256, 220): 262,
 (78, 77): 263,
 (220, 64): 264,
 (81, 68): 265,
 (64, 83): 266,
 (82, 83): 267,
 (68, 77): 268,
 (78, 81): 269,
 (259, 71): 270,
 (198, 198): 271,
 (220, 66): 272,
 (75, 68): 273,
 (220, 82): 274,
 (72, 83): 275,
 (64, 77): 276,
 (64, 81): 277,
 (64, 75): 278,
 (270, 68): 279,
 (26, 198): 280,
 (220, 79): 281,
 (220, 69): 282,
 (78, 84): 283,
 (220, 28): 284,
 (72, 82): 285,
 (257, 262): 286,
 (258, 70): 287,
 (68, 82): 288,
 (220, 86): 289,
 (72, 263): 290,
 (68, 67): 291,
 (72, 66): 292,
 (220, 65): 293,
 (220, 67): 294,
 (68, 83): 295,
 (220, 76): 296,
 (220, 78): 297,
 (197, 197): 298,
 (81, 78): 299,
 (64, 82): 300,
 (68, 75): 301,
 (66, 83): 302,
 (77, 67): 303,
 (220, 258): 304,
 (220, 71): 305,
 (268, 83): 306,
 (72, 67): 307,
 (220, 77): 308,
 (64, 76): 309,
 (260, 262): 310,
 (259, 78): 311,
 (220, 265): 312,
 (12, 12): 313,
 (220, 90): 314,
 (297, 69): 31

In [5]:
enc._mergeable_ranks

{b'!': 0,
 b'"': 1,
 b'#': 2,
 b'$': 3,
 b'%': 4,
 b'&': 5,
 b"'": 6,
 b'(': 7,
 b')': 8,
 b'*': 9,
 b'+': 10,
 b',': 11,
 b'-': 12,
 b'.': 13,
 b'/': 14,
 b'0': 15,
 b'1': 16,
 b'2': 17,
 b'3': 18,
 b'4': 19,
 b'5': 20,
 b'6': 21,
 b'7': 22,
 b'8': 23,
 b'9': 24,
 b':': 25,
 b';': 26,
 b'<': 27,
 b'=': 28,
 b'>': 29,
 b'?': 30,
 b'@': 31,
 b'A': 32,
 b'B': 33,
 b'C': 34,
 b'D': 35,
 b'E': 36,
 b'F': 37,
 b'G': 38,
 b'H': 39,
 b'I': 40,
 b'J': 41,
 b'K': 42,
 b'L': 43,
 b'M': 44,
 b'N': 45,
 b'O': 46,
 b'P': 47,
 b'Q': 48,
 b'R': 49,
 b'S': 50,
 b'T': 51,
 b'U': 52,
 b'V': 53,
 b'W': 54,
 b'X': 55,
 b'Y': 56,
 b'Z': 57,
 b'[': 58,
 b'\\': 59,
 b']': 60,
 b'^': 61,
 b'_': 62,
 b'`': 63,
 b'a': 64,
 b'b': 65,
 b'c': 66,
 b'd': 67,
 b'e': 68,
 b'f': 69,
 b'g': 70,
 b'h': 71,
 b'i': 72,
 b'j': 73,
 b'k': 74,
 b'l': 75,
 b'm': 76,
 b'n': 77,
 b'o': 78,
 b'p': 79,
 b'q': 80,
 b'r': 81,
 b's': 82,
 b't': 83,
 b'u': 84,
 b'v': 85,
 b'w': 86,
 b'x': 87,
 b'y': 88,
 b'z': 89,
 b'{': 90,
 b'|': 9

In [12]:
[list(ch.encode('utf-8')) for ch in ['bharat', 'goyal']]

[[98, 104, 97, 114, 97, 116], [103, 111, 121, 97, 108]]